# Generated by Django 3.1.2 on 2021-04-15 19:11

from django.db import migrations, models
import timezone_field.fields
import userAccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=64, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='middle_name')),
                ('bio', models.CharField(blank=True, default='', max_length=500, verbose_name='bio')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is_confirmed')),
                ('dob', models.DateField(blank=True, default='1970-01-01', verbose_name='dob')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Not Set')], default='', max_length=1, verbose_name='gender')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='timezone')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'email'],
            },
            managers=[
                ('objects', userAccount.models.UserModelManager()),
            ],
        ),
    ]
