# Generated by Django 3.1.2 on 2021-04-22 18:24

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='unique_user_token',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=1, min_length=20, prefix=''),
            preserve_default=False,
        ),
    ]
