# Generated by Django 3.1.2 on 2021-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_internaluser_unique_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaluser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='phone'),
        ),
    ]
