# Generated by Django 3.2.5 on 2021-07-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20210422_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internaluser',
            name='unique_user_token',
        ),
    ]
