# Generated by Django 3.2.5 on 2021-07-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('hash', models.CharField(max_length=512)),
                ('timestamp', models.IntegerField(blank=True)),
                ('interval', models.IntegerField(blank=True)),
                ('size', models.IntegerField(blank=True)),
                ('transactionCount', models.IntegerField(blank=True)),
                ('miner', models.CharField(max_length=512)),
                ('reward', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
    ]
