# Generated by Django 3.2.5 on 2021-07-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20210715_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='allow_override_on_update',
            field=models.BooleanField(default=False),
        ),
    ]
