# Generated by Django 3.2.5 on 2021-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_alter_block_iso_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='iso_timestamp',
            field=models.DateTimeField(),
        ),
    ]
