# Generated by Django 3.2.5 on 2021-07-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0008_alter_block_iso_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='allow_override_on_update',
        ),
    ]
