# Generated by Django 3.2.5 on 2021-07-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_remove_block_allow_override_on_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(unique=True),
        ),
    ]
